import { StyleSheet } from "react-native";
import { colors } from "../constants/colors";

export const styles = StyleSheet.create({
  appShell: {
    flex: 1,
    backgroundColor: colors.background,
  },
  screen: {
    flex: 1,
    justifyContent: "center",
    padding: 20,
    backgroundColor: colors.background,
  },
  loginScreen: {
    flex: 1,
    justifyContent: "center",
    padding: 20,
    backgroundColor: colors.background,
  },
  content: {
    flex: 1,
  },
  compactNavbar: {
    minHeight: 40,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  compactBackButton: {
    width: 34,
    height: 34,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 17,
  },
  compactBackIcon: {
    color: colors.navy,
    fontSize: 34,
    fontWeight: "900",
    lineHeight: 34,
  },
  compactNavTitle: {
    flex: 1,
    color: colors.text,
    fontSize: 18,
    fontWeight: "900",
    textAlign: "center",
  },
  compactNavSpacer: {
    width: 34,
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 100,
  },
  dashboardHero: {
    padding: 14,
    borderRadius: 18,
    backgroundColor: colors.navy,
  },
  dashboardHeroProfileRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    marginBottom: 12,
  },
  dashboardHeroProfileButton: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 2,
  },
  heroProfileAvatar: {
    width: 38,
    height: 38,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 19,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.28)",
    backgroundColor: "rgba(255,255,255,0.15)",
  },
  heroProfileAvatarText: {
    color: colors.white,
    fontSize: 13,
    fontWeight: "900",
  },
  heroProfileTextBlock: {
    flex: 1,
    minWidth: 0,
  },
  heroProfileGreeting: {
    color: colors.white,
    fontSize: 15,
    fontWeight: "900",
  },
  heroProfileSubtitle: {
    marginTop: 2,
    color: "#d8d7ff",
    fontSize: 12,
    fontWeight: "800",
  },
  heroEyebrow: {
    color: "#d8d7ff",
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  dashboardTitle: {
    marginTop: 8,
    color: colors.white,
    fontSize: 25,
    fontWeight: "900",
  },
  dashboardSubtitle: {
    marginTop: 5,
    color: "#d8d7ff",
    fontSize: 14,
    fontWeight: "700",
    lineHeight: 20,
  },
  coverageBlock: {
    marginTop: 0,
    padding: 13,
    borderRadius: 14,
    backgroundColor: "rgba(255,255,255,0.12)",
  },
  coverageHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  coverageLabel: {
    color: "#d8d7ff",
    fontSize: 12,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  coverageValue: {
    color: colors.white,
    fontSize: 24,
    fontWeight: "900",
  },
  coverageTrack: {
    height: 8,
    overflow: "hidden",
    marginTop: 10,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.22)",
  },
  coverageFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: colors.orange,
  },
  coverageMeta: {
    marginTop: 8,
    color: "#eeeeff",
    fontSize: 12,
    fontWeight: "800",
  },
  coverageCountText: {
    marginTop: 4,
    color: colors.white,
    fontSize: 12,
    fontWeight: "900",
  },
  loginPanel: {
    padding: 22,
    borderRadius: 16,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    gap: 12,
    shadowColor: "#000000",
    shadowOpacity: 0.08,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
  },
  loginLogoRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 6,
  },
  loginLogoCard: {
    flex: 1,
    height: 64,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: "#ffffff",
  },
  smollanLogo: {
    width: "100%",
    height: 34,
  },
  unileverLogo: {
    width: "100%",
    height: 50,
  },
  eyebrow: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  title: {
    color: colors.text,
    fontSize: 32,
    fontWeight: "800",
  },
  bodyText: {
    color: colors.muted,
    fontSize: 15,
    lineHeight: 22,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  headerTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  logoutButton: {
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.35)",
    backgroundColor: "rgba(255,255,255,0.12)",
  },
  logoutButtonText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: "900",
  },
  label: {
    color: colors.text,
    fontSize: 14,
    fontWeight: "700",
    marginTop: 8,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: "#ffffff",
    color: colors.text,
    fontSize: 16,
  },
  primaryButton: {
    alignItems: "center",
    borderRadius: 12,
    backgroundColor: colors.navy,
    paddingVertical: 14,
    marginTop: 8,
  },
  primaryButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "800",
  },
  disabledButton: {
    opacity: 0.65,
  },
  inlineState: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginTop: 18,
  },
  errorText: {
    color: colors.danger,
    fontSize: 14,
    fontWeight: "700",
    marginVertical: 12,
  },
  filterPanel: {
    marginTop: 18,
    padding: 16,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  filterHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 12,
  },
  filterTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: "900",
  },
  selectedPeriodText: {
    marginBottom: 4,
    color: colors.navy,
    fontSize: 13,
    fontWeight: "900",
  },
  filterLabel: {
    marginTop: 10,
    marginBottom: 8,
    color: colors.text,
    fontSize: 13,
    fontWeight: "800",
  },
  filterRow: {
    gap: 8,
    paddingRight: 12,
  },
  dateRangeRow: {
    flexDirection: "row",
    gap: 10,
  },
  dateInput: {
    flex: 1,
    minHeight: 44,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: "#ffffff",
    color: colors.text,
    fontSize: 14,
    fontWeight: "800",
  },
  filterChip: {
    minWidth: 48,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.navySoft,
  },
  filterChipActive: {
    borderColor: colors.navy,
    backgroundColor: colors.navy,
  },
  filterChipText: {
    color: colors.text,
    fontSize: 13,
    fontWeight: "800",
  },
  filterChipTextActive: {
    color: "#ffffff",
  },
  applyButton: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: colors.navy,
  },
  applyButtonText: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "900",
  },
  statsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginTop: 22,
  },
  statCard: {
    width: "47%",
    padding: 16,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  statLabel: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  statValue: {
    marginTop: 8,
    color: colors.text,
    fontSize: 25,
    fontWeight: "900",
  },
  statDetail: {
    marginTop: 8,
    color: colors.muted,
    fontSize: 12,
    fontWeight: "800",
  },
  panel: {
    marginTop: 18,
    padding: 16,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  panelTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: "800",
  },
  panelSubtitle: {
    marginTop: 3,
    color: colors.muted,
    fontSize: 13,
    fontWeight: "700",
  },
  panelHeaderRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 14,
  },
  reportBadge: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: colors.navySoft,
  },
  reportBadgeText: {
    color: colors.navy,
    fontSize: 12,
    fontWeight: "900",
  },
  reportMetricGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  reportMetric: {
    width: "48%",
    minHeight: 76,
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: "#ffffff",
  },
  reportMetricLabel: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  reportMetricValue: {
    marginTop: 8,
    color: colors.text,
    fontSize: 17,
    fontWeight: "900",
  },
  metricCard: {
    width: "47%",
    minHeight: 100,
    padding: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  metricLabel: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  metricValue: {
    marginTop: 8,
    color: colors.text,
    fontSize: 22,
    fontWeight: "900",
  },
  metricValueSuccess: {
    color: colors.success,
  },
  metricValueWarning: {
    color: colors.orange,
  },
  metricValueCritical: {
    color: colors.danger,
  },
  progressMetricCard: {
    width: "100%",
    minHeight: 88,
    padding: 14,
    borderRadius: 18,
    backgroundColor: colors.navy,
  },
  progressMetricHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  progressMetricLabel: {
    color: "#d8d7ff",
    fontSize: 12,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  progressMetricValue: {
    color: colors.white,
    fontSize: 24,
    fontWeight: "900",
  },
  progressMetricTrack: {
    height: 8,
    overflow: "hidden",
    marginTop: 10,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.22)",
  },
  progressMetricFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: colors.orange,
  },
  focusList: {
    gap: 11,
  },
  focusRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 4,
  },
  focusDotWarning: {
    width: 12,
    height: 12,
    borderRadius: 999,
    backgroundColor: colors.orange,
  },
  focusDotGood: {
    width: 12,
    height: 12,
    borderRadius: 999,
    backgroundColor: colors.success,
  },
  focusDotMuted: {
    width: 12,
    height: 12,
    borderRadius: 999,
    backgroundColor: colors.border,
  },
  focusTextBlock: {
    flex: 1,
    minWidth: 0,
  },
  focusTitle: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: "800",
  },
  focusValue: {
    marginTop: 2,
    color: colors.text,
    fontSize: 18,
    fontWeight: "900",
  },
  quickActionGrid: {
    flexDirection: "row",
    gap: 12,
    marginTop: 18,
  },
  quickActionCard: {
    flex: 1,
    minHeight: 82,
    padding: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  quickActionLabel: {
    color: colors.orange,
    fontSize: 12,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  quickActionTitle: {
    marginTop: 8,
    color: colors.text,
    fontSize: 16,
    fontWeight: "900",
  },
  merchScreen: {
    flex: 1,
  },
  merchScrollContent: {
    padding: 20,
    paddingTop: 88,
    paddingBottom: 100,
  },
  merchSelectedScrollContent: {
    paddingTop: 18,
  },
  merchTopSearchPanel: {
    position: "absolute",
    top: 16,
    left: 16,
    right: 16,
    zIndex: 5,
  },
  merchSearchBox: {
    minHeight: 64,
    paddingHorizontal: 14,
    paddingTop: 8,
    paddingBottom: 7,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    shadowColor: "#000000",
    shadowOpacity: 0.12,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 5,
  },
  merchSearchLabel: {
    color: colors.muted,
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  merchTopSearchInput: {
    minHeight: 36,
    paddingLeft: 0,
    paddingRight: 76,
    color: colors.text,
    fontSize: 16,
    fontWeight: "900",
  },
  merchSearchClear: {
    position: "absolute",
    top: 16,
    right: 9,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 999,
    backgroundColor: colors.navySoft,
  },
  merchSearchClearText: {
    color: colors.navy,
    fontSize: 12,
    fontWeight: "900",
  },
  merchSearchModeHeader: {
    marginBottom: 4,
  },
  merchMainHeader: {
    marginBottom: 4,
  },
  merchMainSubtitle: {
    marginTop: -4,
    marginBottom: 10,
    color: colors.muted,
    fontSize: 13,
    fontWeight: "800",
    textAlign: "center",
  },
  merchSelectedProfileCard: {
    marginBottom: 16,
    padding: 16,
    borderRadius: 18,
    backgroundColor: colors.navy,
    shadowColor: "#000000",
    shadowOpacity: 0.12,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  merchSelectedProfileHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  merchSelectedAvatar: {
    width: 48,
    height: 48,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.28)",
    backgroundColor: "rgba(255,255,255,0.15)",
  },
  merchSelectedAvatarText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: "900",
  },
  merchSelectedProfileTextBlock: {
    flex: 1,
    minWidth: 0,
  },
  merchSelectedProfileLabel: {
    color: "#d8d7ff",
    fontSize: 11,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  merchSelectedProfileName: {
    marginTop: 5,
    color: colors.white,
    fontSize: 20,
    fontWeight: "900",
    lineHeight: 25,
  },
  merchSelectedProfileMeta: {
    marginTop: 6,
    color: "#eeeeff",
    fontSize: 13,
    fontWeight: "800",
    lineHeight: 18,
  },
  merchSelectedProfilePeriod: {
    marginTop: 12,
    alignSelf: "flex-start",
    paddingHorizontal: 11,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.16)",
    color: colors.white,
    fontSize: 12,
    fontWeight: "900",
  },
  merchList: {
    gap: 10,
  },
  merchCard: {
    padding: 13,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: "#ffffff",
  },
  merchandiserCard: {
    padding: 14,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: "#ffffff",
    shadowColor: "#000000",
    shadowOpacity: 0.04,
    shadowRadius: 9,
    shadowOffset: { width: 0, height: 5 },
    elevation: 1,
  },
  merchCardHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
  },
  merchChannelChip: {
    paddingHorizontal: 9,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: colors.navySoft,
  },
  merchChannelChipText: {
    color: colors.navy,
    fontSize: 10,
    fontWeight: "900",
  },
  merchCardMeta: {
    marginTop: 8,
    color: colors.muted,
    fontSize: 12,
    fontWeight: "800",
  },
  merchMetricGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 12,
  },
  merchMetricPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 9,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: "#f8fafc",
  },
  merchMetricPillLabel: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: "900",
  },
  merchMetricPillValue: {
    color: colors.navy,
    fontSize: 11,
    fontWeight: "900",
  },
  merchCardWarning: {
    borderColor: "#fed7aa",
    backgroundColor: "#fff8f1",
  },
  merchStoreList: {
    gap: 10,
  },
  merchStoreCard: {
    padding: 13,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: "#ffffff",
  },
  merchStoreCardPressable: {
    shadowColor: "#000000",
    shadowOpacity: 0.04,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 1,
  },
  merchStoreCardWarning: {
    borderColor: "#fed7aa",
    backgroundColor: "#fff8f1",
  },
  merchStoreVisitCard: {
    padding: 14,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  merchHeaderRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
  },
  merchTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  merchName: {
    color: colors.text,
    fontSize: 15,
    fontWeight: "900",
  },
  merchCode: {
    marginTop: 3,
    color: colors.muted,
    fontSize: 12,
    fontWeight: "800",
  },
  merchMetricRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 10,
  },
  merchMetric: {
    color: colors.navy,
    fontSize: 13,
    fontWeight: "900",
  },
  merchCities: {
    marginTop: 8,
    color: colors.muted,
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 17,
  },
  visitTypeLine: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    marginTop: 10,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: colors.navySoft,
  },
  visitTypeLabel: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: "900",
  },
  visitTypeValue: {
    color: colors.navy,
    fontSize: 11,
    fontWeight: "900",
  },
  storeStatusChipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 7,
    marginTop: 12,
  },
  storeStatusLabel: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: "900",
  },
  storeStatusChip: {
    paddingHorizontal: 9,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: colors.navySoft,
  },
  storeStatusChipCovered: {
    backgroundColor: colors.successSoft,
  },
  storeStatusChipDeviation: {
    backgroundColor: colors.warningSoft,
  },
  storeStatusChipMuted: {
    backgroundColor: colors.navySoft,
  },
  storeStatusChipText: {
    color: colors.navy,
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  storeStatusChipTextCovered: {
    color: colors.success,
  },
  storeStatusChipTextDeviation: {
    color: colors.orange,
  },
  mutedDetailText: {
    color: colors.muted,
  },
  expandedBlock: {
    marginTop: 12,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  inlineActionButton: {
    alignSelf: "flex-start",
    marginTop: 10,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 999,
    backgroundColor: colors.navy,
  },
  inlineActionText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: "900",
  },
  warningPill: {
    paddingHorizontal: 9,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "#ffedd5",
  },
  warningPillText: {
    color: colors.orange,
    fontSize: 10,
    fontWeight: "900",
  },
  deviationBlock: {
    alignItems: "flex-start",
    gap: 7,
    marginTop: 10,
  },
  deviationBadge: {
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: colors.warningSoft,
  },
  deviationBadgeText: {
    color: colors.orange,
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  deviationReasonText: {
    color: colors.text,
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 17,
  },
  storeTapHintRow: {
    marginTop: 12,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  storeTapHintText: {
    color: colors.navy,
    fontSize: 12,
    fontWeight: "900",
  },
  detailText: {
    color: colors.text,
    fontSize: 14,
    lineHeight: 22,
  },
  secondaryButton: {
    alignItems: "center",
    paddingVertical: 13,
    marginTop: 18,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.navy,
    backgroundColor: "#ffffff",
  },
  secondaryButtonText: {
    color: colors.navy,
    fontSize: 15,
    fontWeight: "800",
  },
  storeDetailHero: {
    padding: 16,
    borderRadius: 18,
    backgroundColor: colors.navy,
  },
  storeDetailHeroLabel: {
    color: "#d8d7ff",
    fontSize: 11,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  storeDetailHeroTitle: {
    marginTop: 7,
    color: colors.white,
    fontSize: 24,
    fontWeight: "900",
    lineHeight: 30,
  },
  storeDetailHeroCode: {
    marginTop: 6,
    color: "#eeeeff",
    fontSize: 13,
    fontWeight: "800",
  },
  storeDetailHeroChipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 10,
  },
  storeDetailHeroChip: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.16)",
  },
  storeDetailHeroChipText: {
    color: colors.white,
    fontSize: 11,
    fontWeight: "900",
  },
  storeDetailHeroMeta: {
    marginTop: 10,
    color: "#eeeeff",
    fontSize: 13,
    fontWeight: "800",
    lineHeight: 19,
  },
  storeDetailInfoGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 16,
  },
  storeDetailInfoCard: {
    width: "48%",
    minHeight: 82,
    padding: 13,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    shadowColor: "#000000",
    shadowOpacity: 0.04,
    shadowRadius: 9,
    shadowOffset: { width: 0, height: 5 },
    elevation: 1,
  },
  storeDetailInfoLabel: {
    color: colors.muted,
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  storeDetailInfoValue: {
    marginTop: 9,
    color: colors.text,
    fontSize: 14,
    fontWeight: "900",
    lineHeight: 19,
  },
  profileHero: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 14,
    marginTop: 18,
    padding: 18,
    borderRadius: 18,
    backgroundColor: colors.navy,
  },
  profileHeroAvatar: {
    width: 60,
    height: 60,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 30,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.28)",
    backgroundColor: "rgba(255,255,255,0.15)",
  },
  profileHeroAvatarText: {
    color: colors.white,
    fontSize: 20,
    fontWeight: "900",
  },
  profileHeroTextBlock: {
    flex: 1,
    minWidth: 0,
  },
  profileHeroName: {
    color: colors.white,
    fontSize: 21,
    fontWeight: "900",
  },
  profileHeroReference: {
    marginTop: 6,
    color: "#d8d7ff",
    fontSize: 12,
    fontWeight: "900",
  },
  profileHeroEmail: {
    marginTop: 5,
    color: "#eeeeff",
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 18,
  },
  profileSectionTitle: {
    marginTop: 20,
    marginBottom: 10,
    color: colors.text,
    fontSize: 16,
    fontWeight: "900",
  },
  profileStatsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  profileStatCard: {
    width: "47%",
    minHeight: 92,
    padding: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    shadowColor: "#000000",
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 2,
  },
  profileStatLabel: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  profileStatValue: {
    marginTop: 10,
    color: colors.text,
    fontSize: 16,
    fontWeight: "900",
    lineHeight: 21,
  },
  profilePerimeterCard: {
    marginTop: 14,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 16,
    backgroundColor: colors.surface,
    shadowColor: "#000000",
    shadowOpacity: 0.05,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  profilePerimeterTitle: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  profilePerimeterValue: {
    marginTop: 10,
    color: colors.text,
    fontSize: 20,
    fontWeight: "900",
    lineHeight: 26,
  },
  profilePerimeterMeta: {
    marginTop: 8,
    color: colors.navy,
    fontSize: 13,
    fontWeight: "900",
  },
  tasksOverviewContent: {
    padding: 20,
    paddingBottom: 110,
    gap: 14,
  },
  tasksHeaderCard: {
    padding: 16,
    borderRadius: 18,
    backgroundColor: colors.navy,
  },
  tasksHeaderTitle: {
    marginTop: 8,
    color: colors.white,
    fontSize: 24,
    fontWeight: "900",
    lineHeight: 30,
  },
  tasksHeaderMeta: {
    marginTop: 6,
    color: "#eeeeff",
    fontSize: 13,
    fontWeight: "800",
    lineHeight: 19,
  },
  tasksHeaderCodeText: {
    marginTop: 4,
    color: "#d8d7ff",
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 17,
  },
  tasksSectionCard: {
    padding: 14,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    shadowColor: "#000000",
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 2,
  },
  tasksSectionHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
    marginBottom: 12,
  },
  tasksSectionTitle: {
    flex: 1,
    color: colors.text,
    fontSize: 18,
    fontWeight: "900",
  },
  tasksCheckTimeRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 12,
  },
  tasksInfoPill: {
    flex: 1,
    minHeight: 64,
    padding: 12,
    borderRadius: 14,
    backgroundColor: colors.navySoft,
  },
  tasksInfoPillLabel: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  tasksInfoPillValue: {
    marginTop: 8,
    color: colors.navy,
    fontSize: 18,
    fontWeight: "900",
  },
  tasksImagePair: {
    flexDirection: "row",
    gap: 10,
  },
  tasksImagePreview: {
    flex: 1,
    minWidth: 0,
  },
  tasksImagePreviewCompact: {
    minHeight: 0,
  },
  tasksSingleImageBlock: {
    width: "100%",
  },
  tasksImageLabel: {
    marginBottom: 7,
    color: colors.muted,
    fontSize: 11,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  tasksImageButton: {
    width: "100%",
    borderRadius: 14,
  },
  tasksImage: {
    width: "100%",
    height: 132,
    borderRadius: 14,
    backgroundColor: colors.navySoft,
  },
  tasksImageCompact: {
    height: 104,
    borderRadius: 12,
  },
  tasksImagePlaceholder: {
    width: "100%",
    height: 132,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.navySoft,
  },
  tasksImagePlaceholderText: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: "900",
  },
  tasksImageMeta: {
    marginTop: 7,
    color: colors.muted,
    fontSize: 11,
    fontWeight: "800",
  },
  tasksImageModalBackdrop: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 44,
    paddingBottom: 28,
    backgroundColor: "rgba(5,10,28,0.96)",
  },
  tasksImageModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 16,
  },
  tasksImageModalTitle: {
    flex: 1,
    color: colors.white,
    fontSize: 17,
    fontWeight: "900",
  },
  tasksImageModalClose: {
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.14)",
  },
  tasksImageModalCloseText: {
    color: colors.white,
    fontSize: 13,
    fontWeight: "900",
  },
  tasksImageModalImage: {
    flex: 1,
    width: "100%",
  },
  tasksImageModalMeta: {
    marginTop: 12,
    color: "#eeeeff",
    fontSize: 13,
    fontWeight: "800",
    textAlign: "center",
  },
  tasksSourceBadge: {
    maxWidth: 180,
    paddingHorizontal: 9,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: colors.successSoft,
  },
  tasksSourceBadgeFallback: {
    backgroundColor: colors.warningSoft,
  },
  tasksSourceBadgeEmpty: {
    backgroundColor: colors.navySoft,
  },
  tasksSourceBadgeDark: {
    alignSelf: "flex-start",
    marginTop: 8,
    backgroundColor: "rgba(255,255,255,0.16)",
  },
  tasksSourceBadgeText: {
    color: colors.success,
    fontSize: 10,
    fontWeight: "900",
  },
  tasksSourceBadgeTextFallback: {
    color: colors.orange,
  },
  tasksSourceBadgeTextEmpty: {
    color: colors.muted,
  },
  tasksSourceBadgeTextDark: {
    color: colors.white,
  },
  tasksCardStack: {
    gap: 12,
  },
  tasksCategoryCard: {
    padding: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: "#ffffff",
  },
  tasksCategoryTitle: {
    marginBottom: 10,
    color: colors.text,
    fontSize: 15,
    fontWeight: "900",
    lineHeight: 20,
  },
  tasksProgressCard: {
    padding: 15,
    borderRadius: 18,
    backgroundColor: colors.navy,
  },
  tasksProgressHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  tasksProgressTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  tasksProgressLabel: {
    color: "#d8d7ff",
    fontSize: 13,
    fontWeight: "900",
  },
  tasksProgressValue: {
    color: colors.white,
    fontSize: 28,
    fontWeight: "900",
  },
  tasksProgressTrack: {
    height: 8,
    overflow: "hidden",
    marginTop: 12,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.22)",
  },
  tasksProgressFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: colors.orange,
  },
  tasksProgressMeta: {
    marginTop: 9,
    color: "#eeeeff",
    fontSize: 12,
    fontWeight: "900",
  },
  tasksDetailsButton: {
    alignSelf: "flex-start",
    marginTop: 12,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.14)",
  },
  tasksDetailsButtonText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: "900",
  },
  tasksExpandedContent: {
    marginTop: 12,
  },
  tasksCategoryList: {
    gap: 9,
  },
  tasksProgressCategoryCard: {
    padding: 11,
    borderRadius: 13,
    backgroundColor: colors.surface,
  },
  tasksProgressCategoryHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
  },
  tasksProgressCategoryTitle: {
    flex: 1,
    color: colors.text,
    fontSize: 13,
    fontWeight: "900",
    lineHeight: 18,
  },
  tasksProgressCategoryValue: {
    color: colors.navy,
    fontSize: 15,
    fontWeight: "900",
  },
  tasksSmallProgressTrack: {
    height: 6,
    overflow: "hidden",
    marginTop: 9,
    borderRadius: 999,
    backgroundColor: colors.navySoft,
  },
  tasksSmallProgressFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: colors.orange,
  },
  tasksProgressCategoryMeta: {
    marginTop: 7,
    color: colors.muted,
    fontSize: 11,
    fontWeight: "900",
  },
  tasksQualityGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  tasksEmptyText: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: "800",
    lineHeight: 19,
  },
  tasksEmptyTextDark: {
    color: "#eeeeff",
  },
  mapScreen: {
    flex: 1,
  },
  map: {
    flex: 1,
  },
  mapSearchPanel: {
    position: "absolute",
    top: 16,
    left: 16,
    right: 16,
    zIndex: 5,
    gap: 8,
  },
  storeMapNavbar: {
    minHeight: 38,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 2,
  },
  mapSearchInputWrap: {
    position: "relative",
  },
  mapLoadingPill: {
    position: "absolute",
    top: 12,
    right: 14,
    zIndex: 6,
  },
  mapSearchInput: {
    height: 54,
    paddingLeft: 18,
    paddingRight: 76,
    paddingVertical: 0,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    color: colors.text,
    fontSize: 16,
    fontWeight: "800",
    textAlignVertical: "center",
    shadowColor: "#000000",
    shadowOpacity: 0.16,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 6,
  },
  mapSearchClear: {
    position: "absolute",
    top: 9,
    right: 9,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
    borderRadius: 999,
    backgroundColor: colors.navySoft,
  },
  mapSearchClearText: {
    color: colors.navy,
    fontSize: 12,
    fontWeight: "900",
  },
  mapSearchResults: {
    overflow: "hidden",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    shadowColor: "#000000",
    shadowOpacity: 0.1,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  storeModeRow: {
    flexDirection: "row",
    gap: 8,
  },
  storeModeButton: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  storeModeButtonActive: {
    borderColor: colors.navy,
    backgroundColor: colors.navy,
  },
  storeModeText: {
    color: colors.text,
    fontSize: 13,
    fontWeight: "900",
  },
  storeModeTextActive: {
    color: colors.white,
  },
  storeListContent: {
    padding: 16,
    paddingTop: 230,
    paddingBottom: 110,
  },
  storeStatusFilterRow: {
    flexDirection: "row",
    gap: 8,
  },
  storeStatusFilterChip: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 36,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  storeStatusFilterChipActive: {
    borderColor: colors.navy,
    backgroundColor: colors.navy,
  },
  storeStatusFilterText: {
    color: colors.text,
    fontSize: 11,
    fontWeight: "900",
  },
  storeStatusFilterTextActive: {
    color: colors.white,
  },
  statusFilterRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 14,
  },
  statusFilterChip: {
    paddingHorizontal: 11,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  statusFilterChipActive: {
    borderColor: colors.navy,
    backgroundColor: colors.navy,
  },
  statusFilterText: {
    color: colors.text,
    fontSize: 11,
    fontWeight: "900",
  },
  statusFilterTextActive: {
    color: colors.white,
  },
  storeCardList: {
    gap: 10,
  },
  storeListCard: {
    padding: 14,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    shadowColor: "#000000",
    shadowOpacity: 0.04,
    shadowRadius: 9,
    shadowOffset: { width: 0, height: 5 },
    elevation: 1,
  },
  storeListCardTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: "900",
  },
  storeListCardSubtitle: {
    marginTop: 4,
    color: colors.navy,
    fontSize: 12,
    fontWeight: "900",
  },
  storeListCardMeta: {
    marginTop: 8,
    color: colors.muted,
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 17,
  },
  storeListChipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 12,
  },
  storeBadge: {
    paddingHorizontal: 9,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: colors.navySoft,
  },
  storeBadgeSuccess: {
    backgroundColor: colors.successSoft,
  },
  storeBadgeWarning: {
    backgroundColor: colors.warningSoft,
  },
  storeBadgeText: {
    color: colors.navy,
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  storeBadgeTextSuccess: {
    color: colors.success,
  },
  storeBadgeTextWarning: {
    color: colors.orange,
  },
  storeInfoChip: {
    flex: 1,
    minWidth: 0,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 13,
    backgroundColor: colors.navySoft,
  },
  storeInfoChipLabel: {
    color: colors.muted,
    fontSize: 9,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  storeInfoChipValue: {
    marginTop: 4,
    color: colors.navy,
    fontSize: 11,
    fontWeight: "900",
  },
  storeListActionText: {
    marginTop: 11,
    color: colors.navy,
    fontSize: 12,
    fontWeight: "900",
  },
  storeListActionTextMuted: {
    color: colors.muted,
  },
  storeListAssignmentText: {
    marginTop: 10,
    color: colors.muted,
    fontSize: 12,
    fontWeight: "800",
  },
  storeCard: {
    padding: 13,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  storeRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
  },
  mapSearchResult: {
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  mapSearchResultName: {
    color: colors.text,
    fontSize: 14,
    fontWeight: "900",
  },
  mapSearchResultCode: {
    marginTop: 3,
    color: colors.muted,
    fontSize: 12,
    fontWeight: "700",
  },
  locationControls: {
    position: "absolute",
    right: 16,
    bottom: 28,
    zIndex: 4,
    alignItems: "flex-end",
    gap: 8,
  },
  locationButton: {
    width: 54,
    height: 54,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 999,
    backgroundColor: colors.navy,
    shadowColor: "#000000",
    shadowOpacity: 0.22,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 9 },
    elevation: 7,
  },
  locationButtonText: {
    color: "#ffffff",
    fontSize: 27,
    fontWeight: "900",
    lineHeight: 30,
  },
  locationMessage: {
    maxWidth: 190,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  locationMessageText: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: "700",
  },
  storeSheet: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    overflow: "hidden",
    paddingHorizontal: 22,
    paddingTop: 8,
    paddingBottom: 10,
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    shadowColor: "#000000",
    shadowOpacity: 0.16,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: -8 },
    elevation: 8,
  },
  storeSheetContentWrap: {
    flex: 1,
    minHeight: 0,
  },
  storeSheetScrollContent: {
    paddingBottom: 36,
  },
  storeSheetMeasuredContent: {
    gap: 0,
  },
  storeSheetExpanded: {
    minHeight: 450,
    paddingBottom: 34,
  },
  storeSheetDragArea: {
    marginHorizontal: -4,
    paddingHorizontal: 4,
  },
  sheetHandleButton: {
    alignSelf: "center",
    width: 96,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  sheetHandle: {
    alignSelf: "center",
    width: 44,
    height: 5,
    borderRadius: 999,
    backgroundColor: colors.border,
    marginBottom: 10,
  },
  storeSheetHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  storeSheetTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  sheetTitle: {
    color: colors.text,
    fontSize: 22,
    fontWeight: "900",
  },
  storeCodeText: {
    marginTop: 4,
    color: colors.muted,
    fontSize: 14,
    fontWeight: "800",
  },
  storeSheetMetaText: {
    marginTop: 7,
    color: colors.muted,
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 17,
  },
  storeSheetSummary: {
    marginTop: 10,
    padding: 12,
    borderRadius: 15,
    backgroundColor: colors.navySoft,
  },
  storeSheetInfoStack: {
    gap: 7,
  },
  storeSheetInfoRow: {
    minHeight: 38,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 12,
    backgroundColor: colors.surface,
  },
  storeSheetInfoLabel: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: "900",
  },
  storeSheetInfoValue: {
    flex: 1,
    color: colors.navy,
    fontSize: 12,
    fontWeight: "900",
    textAlign: "right",
  },
  storeSheetReasonText: {
    marginTop: 8,
    color: colors.text,
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 17,
  },
  storeSheetBadgeRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 7,
  },
  storeSheetChipRow: {
    flexDirection: "row",
    gap: 8,
  },
  storeSheetDateText: {
    marginTop: 9,
    color: colors.muted,
    fontSize: 12,
    fontWeight: "800",
  },
  storeSheetActionText: {
    color: colors.navy,
    fontSize: 12,
    fontWeight: "900",
  },
  storeSheetActionButton: {
    alignSelf: "flex-start",
    marginTop: 10,
    paddingHorizontal: 11,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: colors.surface,
  },
  storeSheetActionButtonDisabled: {
    backgroundColor: "#f3f4f6",
  },
  storeSheetActionTextDisabled: {
    color: colors.muted,
  },
  storeSheetLoadingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 10,
  },
  storeSheetLoadingText: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: "800",
  },
  storeSheetCompactDetails: {
    flexDirection: "row",
    gap: 10,
    marginTop: 10,
  },
  statusPill: {
    minWidth: 112,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
  },
  statusPillGood: {
    backgroundColor: "#e7f7ee",
  },
  statusPillWarning: {
    backgroundColor: "#fff3e7",
  },
  statusPillMuted: {
    backgroundColor: colors.navySoft,
  },
  statusPillText: {
    color: colors.navy,
    fontSize: 12,
    fontWeight: "900",
    textAlign: "center",
  },
  statusPillLabel: {
    color: colors.muted,
    fontSize: 8,
    fontWeight: "900",
    textAlign: "center",
    textTransform: "uppercase",
  },
  osaBlock: {
    marginTop: 10,
    paddingHorizontal: 13,
    paddingTop: 10,
    paddingBottom: 10,
    borderRadius: 15,
    backgroundColor: colors.navySoft,
  },
  osaValue: {
    marginTop: 2,
    color: colors.navy,
    fontSize: 26,
    fontWeight: "900",
  },
  osaTrack: {
    height: 7,
    marginTop: 8,
    overflow: "hidden",
    borderRadius: 999,
    backgroundColor: "#ffffff",
  },
  osaFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: colors.navy,
  },
  storeMetricGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 14,
  },
  storeDetailsSectionTitle: {
    width: "100%",
    marginTop: 4,
    marginBottom: 2,
    color: colors.text,
    fontSize: 14,
    fontWeight: "900",
  },
  storeDetailsPanel: {
    overflow: "hidden",
    marginTop: 0,
  },
  storeDetailsScrollContent: {
    paddingTop: 10,
    paddingBottom: 24,
  },
  storeMetric: {
    width: "48%",
    minHeight: 74,
    padding: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: "#ffffff",
  },
  storeMetricLabel: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  storeMetricValue: {
    marginTop: 7,
    color: colors.text,
    fontSize: 15,
    fontWeight: "900",
  },
  storeDetailsError: {
    marginTop: 12,
    color: colors.danger,
    fontSize: 13,
    fontWeight: "800",
  },
  sectionHeader: {
    marginTop: 18,
    marginBottom: 8,
    color: colors.text,
    fontSize: 16,
    fontWeight: "900",
  },
  emptyStateText: {
    marginTop: 18,
    color: colors.muted,
    fontSize: 14,
    fontWeight: "800",
    lineHeight: 20,
  },
  tabs: {
    flexDirection: "row",
    gap: 10,
    padding: 12,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    backgroundColor: colors.surface,
  },
  tabButton: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 48,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: colors.navySoft,
  },
  tabButtonActive: {
    backgroundColor: colors.navy,
  },
  tabButtonText: {
    color: colors.text,
    fontWeight: "800",
  },
  tabButtonTextActive: {
    color: "#ffffff",
  },
  tabBadge: {
    position: "absolute",
    top: 4,
    right: 8,
    minWidth: 18,
    overflow: "hidden",
    paddingHorizontal: 5,
    paddingVertical: 2,
    borderRadius: 999,
    backgroundColor: colors.orange,
    color: colors.white,
    fontSize: 10,
    fontWeight: "900",
    textAlign: "center",
  },
  tabBadgeActive: {
    backgroundColor: colors.white,
    color: colors.navy,
  },
});
