import { StyleSheet } from "react-native";
import { colors } from "../constants/colors";

export const styles = StyleSheet.create({
  appShell: {
    flex: 1,
    backgroundColor: colors.background,
  },
  screen: {
    flex: 1,
    justifyContent: "center",
    padding: 20,
    backgroundColor: colors.background,
  },
  content: {
    flex: 1,
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 100,
  },
  dashboardHero: {
    padding: 18,
    borderRadius: 18,
    backgroundColor: colors.navy,
  },
  heroEyebrow: {
    color: "#d8d7ff",
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  dashboardTitle: {
    marginTop: 8,
    color: colors.white,
    fontSize: 25,
    fontWeight: "900",
  },
  dashboardSubtitle: {
    marginTop: 5,
    color: "#d8d7ff",
    fontSize: 14,
    fontWeight: "700",
    lineHeight: 20,
  },
  coverageBlock: {
    marginTop: 18,
    padding: 13,
    borderRadius: 14,
    backgroundColor: "rgba(255,255,255,0.12)",
  },
  coverageHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  coverageLabel: {
    color: "#d8d7ff",
    fontSize: 12,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  coverageValue: {
    color: colors.white,
    fontSize: 24,
    fontWeight: "900",
  },
  coverageTrack: {
    height: 8,
    overflow: "hidden",
    marginTop: 10,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.22)",
  },
  coverageFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: colors.orange,
  },
  coverageMeta: {
    marginTop: 8,
    color: "#eeeeff",
    fontSize: 12,
    fontWeight: "800",
  },
  loginPanel: {
    padding: 22,
    borderRadius: 18,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    gap: 12,
  },
  eyebrow: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  title: {
    color: colors.text,
    fontSize: 32,
    fontWeight: "800",
  },
  bodyText: {
    color: colors.muted,
    fontSize: 15,
    lineHeight: 22,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  headerTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  logoutButton: {
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.35)",
    backgroundColor: "rgba(255,255,255,0.12)",
  },
  logoutButtonText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: "900",
  },
  label: {
    color: colors.text,
    fontSize: 14,
    fontWeight: "700",
    marginTop: 8,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: "#ffffff",
    color: colors.text,
    fontSize: 16,
  },
  primaryButton: {
    alignItems: "center",
    borderRadius: 12,
    backgroundColor: colors.navy,
    paddingVertical: 14,
    marginTop: 8,
  },
  primaryButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "800",
  },
  disabledButton: {
    opacity: 0.65,
  },
  inlineState: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginTop: 18,
  },
  errorText: {
    color: colors.danger,
    fontSize: 14,
    fontWeight: "700",
    marginVertical: 12,
  },
  filterPanel: {
    marginTop: 18,
    padding: 16,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  filterHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 12,
  },
  filterTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: "900",
  },
  selectedPeriodText: {
    marginBottom: 4,
    color: colors.navy,
    fontSize: 13,
    fontWeight: "900",
  },
  filterLabel: {
    marginTop: 10,
    marginBottom: 8,
    color: colors.text,
    fontSize: 13,
    fontWeight: "800",
  },
  filterRow: {
    gap: 8,
    paddingRight: 12,
  },
  dateRangeRow: {
    flexDirection: "row",
    gap: 10,
  },
  dateInput: {
    flex: 1,
    minHeight: 44,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: "#ffffff",
    color: colors.text,
    fontSize: 14,
    fontWeight: "800",
  },
  filterChip: {
    minWidth: 48,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.navySoft,
  },
  filterChipActive: {
    borderColor: colors.navy,
    backgroundColor: colors.navy,
  },
  filterChipText: {
    color: colors.text,
    fontSize: 13,
    fontWeight: "800",
  },
  filterChipTextActive: {
    color: "#ffffff",
  },
  applyButton: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: colors.navy,
  },
  applyButtonText: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "900",
  },
  statsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginTop: 22,
  },
  statCard: {
    width: "47%",
    padding: 16,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  statLabel: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  statValue: {
    marginTop: 8,
    color: colors.text,
    fontSize: 25,
    fontWeight: "900",
  },
  statDetail: {
    marginTop: 8,
    color: colors.muted,
    fontSize: 12,
    fontWeight: "800",
  },
  panel: {
    marginTop: 18,
    padding: 16,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  panelTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: "800",
  },
  panelSubtitle: {
    marginTop: 3,
    color: colors.muted,
    fontSize: 13,
    fontWeight: "700",
  },
  panelHeaderRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 14,
  },
  reportBadge: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: colors.navySoft,
  },
  reportBadgeText: {
    color: colors.navy,
    fontSize: 12,
    fontWeight: "900",
  },
  reportMetricGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  reportMetric: {
    width: "48%",
    minHeight: 76,
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: "#ffffff",
  },
  reportMetricLabel: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  reportMetricValue: {
    marginTop: 8,
    color: colors.text,
    fontSize: 17,
    fontWeight: "900",
  },
  metricCard: {
    width: "47%",
    minHeight: 100,
    padding: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  metricLabel: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  metricValue: {
    marginTop: 8,
    color: colors.text,
    fontSize: 22,
    fontWeight: "900",
  },
  metricValueSuccess: {
    color: colors.success,
  },
  metricValueWarning: {
    color: colors.orange,
  },
  metricValueCritical: {
    color: colors.danger,
  },
  focusList: {
    gap: 11,
  },
  focusRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 4,
  },
  focusDotWarning: {
    width: 12,
    height: 12,
    borderRadius: 999,
    backgroundColor: colors.orange,
  },
  focusDotGood: {
    width: 12,
    height: 12,
    borderRadius: 999,
    backgroundColor: colors.success,
  },
  focusDotMuted: {
    width: 12,
    height: 12,
    borderRadius: 999,
    backgroundColor: colors.border,
  },
  focusTextBlock: {
    flex: 1,
    minWidth: 0,
  },
  focusTitle: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: "800",
  },
  focusValue: {
    marginTop: 2,
    color: colors.text,
    fontSize: 18,
    fontWeight: "900",
  },
  quickActionGrid: {
    flexDirection: "row",
    gap: 12,
    marginTop: 18,
  },
  quickActionCard: {
    flex: 1,
    minHeight: 82,
    padding: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  quickActionLabel: {
    color: colors.orange,
    fontSize: 12,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  quickActionTitle: {
    marginTop: 8,
    color: colors.text,
    fontSize: 16,
    fontWeight: "900",
  },
  merchScreen: {
    flex: 1,
  },
  merchScrollContent: {
    padding: 20,
    paddingTop: 88,
    paddingBottom: 100,
  },
  merchTopSearchPanel: {
    position: "absolute",
    top: 16,
    left: 16,
    right: 16,
    zIndex: 5,
  },
  merchSearchBox: {
    minHeight: 64,
    paddingHorizontal: 14,
    paddingTop: 8,
    paddingBottom: 7,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    shadowColor: "#000000",
    shadowOpacity: 0.12,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 5,
  },
  merchSearchLabel: {
    color: colors.muted,
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  merchTopSearchInput: {
    minHeight: 36,
    paddingLeft: 0,
    paddingRight: 76,
    color: colors.text,
    fontSize: 16,
    fontWeight: "900",
  },
  merchSearchClear: {
    position: "absolute",
    top: 16,
    right: 9,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 999,
    backgroundColor: colors.navySoft,
  },
  merchSearchClearText: {
    color: colors.navy,
    fontSize: 12,
    fontWeight: "900",
  },
  merchSearchModeHeader: {
    marginBottom: 4,
  },
  merchTopBackNav: {
    minHeight: 58,
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    gap: 8,
    paddingHorizontal: 16,
    borderRadius: 18,
    backgroundColor: colors.navy,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 4,
  },
  merchTopBackIcon: {
    color: "#ffffff",
    fontSize: 22,
    fontWeight: "900",
    lineHeight: 24,
  },
  merchTopBackText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "900",
  },
  merchList: {
    gap: 10,
  },
  merchCard: {
    padding: 13,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: "#ffffff",
  },
  merchandiserCard: {
    padding: 13,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: "#ffffff",
  },
  merchCardWarning: {
    borderColor: "#fed7aa",
    backgroundColor: "#fff8f1",
  },
  merchStoreList: {
    gap: 10,
  },
  merchStoreCard: {
    padding: 13,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: "#ffffff",
  },
  merchStoreCardWarning: {
    borderColor: "#fed7aa",
    backgroundColor: "#fff8f1",
  },
  merchHeaderRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
  },
  merchTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  merchName: {
    color: colors.text,
    fontSize: 15,
    fontWeight: "900",
  },
  merchCode: {
    marginTop: 3,
    color: colors.muted,
    fontSize: 12,
    fontWeight: "800",
  },
  merchMetricRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 10,
  },
  merchMetric: {
    color: colors.navy,
    fontSize: 13,
    fontWeight: "900",
  },
  merchCities: {
    marginTop: 8,
    color: colors.muted,
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 17,
  },
  merchReasons: {
    marginTop: 6,
    color: colors.orange,
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 17,
  },
  mutedDetailText: {
    color: colors.muted,
  },
  expandedBlock: {
    marginTop: 12,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  inlineActionButton: {
    alignSelf: "flex-start",
    marginTop: 10,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 999,
    backgroundColor: colors.navy,
  },
  inlineActionText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: "900",
  },
  warningPill: {
    paddingHorizontal: 9,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "#ffedd5",
  },
  warningPillText: {
    color: colors.orange,
    fontSize: 10,
    fontWeight: "900",
  },
  detailText: {
    color: colors.text,
    fontSize: 14,
    lineHeight: 22,
  },
  secondaryButton: {
    alignItems: "center",
    paddingVertical: 13,
    marginTop: 18,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.navy,
    backgroundColor: "#ffffff",
  },
  secondaryButtonText: {
    color: colors.navy,
    fontSize: 15,
    fontWeight: "800",
  },
  mapScreen: {
    flex: 1,
  },
  map: {
    flex: 1,
  },
  mapSearchPanel: {
    position: "absolute",
    top: 16,
    left: 16,
    right: 16,
    zIndex: 5,
    gap: 8,
  },
  mapLoadingPill: {
    position: "absolute",
    top: 12,
    right: 14,
    zIndex: 6,
  },
  mapSearchInput: {
    minHeight: 54,
    paddingLeft: 18,
    paddingRight: 76,
    paddingVertical: 13,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    color: colors.text,
    fontSize: 16,
    fontWeight: "800",
    shadowColor: "#000000",
    shadowOpacity: 0.16,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 6,
  },
  mapSearchClear: {
    position: "absolute",
    top: 8,
    right: 9,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 999,
    backgroundColor: colors.navySoft,
  },
  mapSearchClearText: {
    color: colors.navy,
    fontSize: 12,
    fontWeight: "900",
  },
  mapSearchResults: {
    overflow: "hidden",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    shadowColor: "#000000",
    shadowOpacity: 0.1,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  storeModeRow: {
    flexDirection: "row",
    gap: 8,
  },
  storeModeButton: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  storeModeButtonActive: {
    borderColor: colors.navy,
    backgroundColor: colors.navy,
  },
  storeModeText: {
    color: colors.text,
    fontSize: 13,
    fontWeight: "900",
  },
  storeModeTextActive: {
    color: colors.white,
  },
  storeListContent: {
    padding: 16,
    paddingTop: 136,
    paddingBottom: 110,
  },
  statusFilterRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 14,
  },
  statusFilterChip: {
    paddingHorizontal: 11,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  statusFilterChipActive: {
    borderColor: colors.navy,
    backgroundColor: colors.navy,
  },
  statusFilterText: {
    color: colors.text,
    fontSize: 11,
    fontWeight: "900",
  },
  statusFilterTextActive: {
    color: colors.white,
  },
  storeCardList: {
    gap: 10,
  },
  storeCard: {
    padding: 13,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  storeRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
  },
  mapSearchResult: {
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  mapSearchResultName: {
    color: colors.text,
    fontSize: 14,
    fontWeight: "900",
  },
  mapSearchResultCode: {
    marginTop: 3,
    color: colors.muted,
    fontSize: 12,
    fontWeight: "700",
  },
  locationControls: {
    position: "absolute",
    right: 16,
    bottom: 24,
    zIndex: 4,
    alignItems: "flex-end",
    gap: 8,
  },
  locationButton: {
    width: 48,
    height: 48,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 999,
    backgroundColor: colors.navy,
    shadowColor: "#000000",
    shadowOpacity: 0.16,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 5,
  },
  locationButtonText: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "900",
  },
  locationMessage: {
    maxWidth: 190,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  locationMessageText: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: "700",
  },
  storeSheet: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    overflow: "hidden",
    paddingHorizontal: 22,
    paddingTop: 8,
    paddingBottom: 10,
    minHeight: 150,
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    shadowColor: "#000000",
    shadowOpacity: 0.16,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: -8 },
    elevation: 8,
  },
  storeSheetExpanded: {
    minHeight: 450,
    paddingBottom: 34,
  },
  storeSheetDragArea: {
    marginHorizontal: -4,
    paddingHorizontal: 4,
  },
  sheetHandleButton: {
    alignSelf: "center",
    width: 96,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  sheetHandle: {
    alignSelf: "center",
    width: 44,
    height: 5,
    borderRadius: 999,
    backgroundColor: colors.border,
    marginBottom: 10,
  },
  storeSheetHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  storeSheetTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  sheetTitle: {
    color: colors.text,
    fontSize: 22,
    fontWeight: "900",
  },
  storeCodeText: {
    marginTop: 4,
    color: colors.muted,
    fontSize: 14,
    fontWeight: "800",
  },
  statusPill: {
    minWidth: 112,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
  },
  statusPillGood: {
    backgroundColor: "#e7f7ee",
  },
  statusPillWarning: {
    backgroundColor: "#fff3e7",
  },
  statusPillMuted: {
    backgroundColor: colors.navySoft,
  },
  statusPillText: {
    color: colors.navy,
    fontSize: 12,
    fontWeight: "900",
    textAlign: "center",
  },
  statusPillLabel: {
    color: colors.muted,
    fontSize: 8,
    fontWeight: "900",
    textAlign: "center",
    textTransform: "uppercase",
  },
  statusBadge: {
    alignSelf: "flex-start",
    minWidth: 82,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 999,
  },
  coverageStatusBadge: {
    minWidth: 104,
  },
  statusBadgeText: {
    color: colors.navy,
    fontSize: 10,
    fontWeight: "900",
    textAlign: "center",
    textTransform: "uppercase",
  },
  statusBadgeCovered: {
    backgroundColor: "#dcfce7",
  },
  statusBadgeNonVisited: {
    backgroundColor: "#fef3c7",
  },
  statusBadgeDeviation: {
    backgroundColor: "#fee2e2",
  },
  statusBadgeRejected: {
    backgroundColor: "#e5e7eb",
  },
  statusBadgeGps: {
    backgroundColor: "#fef08a",
  },
  statusBadgeMuted: {
    backgroundColor: colors.navySoft,
  },
  osaBlock: {
    marginTop: 10,
    paddingHorizontal: 13,
    paddingTop: 10,
    paddingBottom: 10,
    borderRadius: 15,
    backgroundColor: colors.navySoft,
  },
  osaValue: {
    marginTop: 2,
    color: colors.navy,
    fontSize: 26,
    fontWeight: "900",
  },
  osaTrack: {
    height: 7,
    marginTop: 8,
    overflow: "hidden",
    borderRadius: 999,
    backgroundColor: "#ffffff",
  },
  osaFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: colors.navy,
  },
  storeMetricGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 14,
  },
  storeDetailsSectionTitle: {
    width: "100%",
    marginTop: 4,
    marginBottom: 2,
    color: colors.text,
    fontSize: 14,
    fontWeight: "900",
  },
  storeDetailsPanel: {
    overflow: "hidden",
    marginTop: 0,
  },
  storeDetailsScrollContent: {
    paddingTop: 10,
    paddingBottom: 24,
  },
  storeMetric: {
    width: "48%",
    minHeight: 74,
    padding: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: "#ffffff",
  },
  storeMetricWarning: {
    borderColor: "#fcd34d",
    backgroundColor: "#fffbeb",
  },
  storeMetricLabel: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  storeMetricValue: {
    marginTop: 7,
    color: colors.text,
    fontSize: 15,
    fontWeight: "900",
  },
  storeDetailsError: {
    marginTop: 12,
    color: colors.danger,
    fontSize: 13,
    fontWeight: "800",
  },
  sectionHeader: {
    marginTop: 18,
    marginBottom: 8,
    color: colors.text,
    fontSize: 16,
    fontWeight: "900",
  },
  issueList: {
    gap: 10,
    marginTop: 18,
  },
  issueCard: {
    padding: 13,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  issueTypeBadge: {
    alignSelf: "flex-start",
    minWidth: 98,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 999,
  },
  emptyStateText: {
    marginTop: 18,
    color: colors.muted,
    fontSize: 14,
    fontWeight: "800",
    lineHeight: 20,
  },
  tabs: {
    flexDirection: "row",
    gap: 10,
    padding: 12,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    backgroundColor: colors.surface,
  },
  tabButton: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 48,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: colors.navySoft,
  },
  tabButtonActive: {
    backgroundColor: colors.navy,
  },
  tabButtonText: {
    color: colors.text,
    fontWeight: "800",
  },
  tabButtonTextActive: {
    color: "#ffffff",
  },
  tabBadge: {
    position: "absolute",
    top: 4,
    right: 8,
    minWidth: 18,
    overflow: "hidden",
    paddingHorizontal: 5,
    paddingVertical: 2,
    borderRadius: 999,
    backgroundColor: colors.orange,
    color: colors.white,
    fontSize: 10,
    fontWeight: "900",
    textAlign: "center",
  },
  tabBadgeActive: {
    backgroundColor: colors.white,
    color: colors.navy,
  },
});
